#compdef o2c

autoload -U is-at-least

_o2c() {
    typeset -A opt_args
    typeset -a _arguments_options
    local ret=1

    if is-at-least 5.2; then
        _arguments_options=(-s -S -C)
    else
        _arguments_options=(-s -C)
    fi

    local context curcontext="$curcontext" state line
    _arguments "${_arguments_options[@]}" : \
'-o+[The output path for the compiled binary]:OUT_FILE:_files' \
'--display-tokens[Display the tokens generated by the compilation]' \
'--display-ast[Display the AST generated from by the compilation]' \
'-h[Print help]' \
'--help[Print help]' \
'-V[Print version]' \
'--version[Print version]' \
':oxygen_file -- The path to the oxygen file to compile:_files' \
&& ret=0
}

(( $+functions[_o2c_commands] )) ||
_o2c_commands() {
    local commands; commands=()
    _describe -t commands 'o2c commands' commands "$@"
}

if [ "$funcstack[1]" = "_o2c" ]; then
    _o2c "$@"
else
    compdef _o2c o2c
fi
#compdef oxygen

autoload -U is-at-least

_oxygen() {
    typeset -A opt_args
    typeset -a _arguments_options
    local ret=1

    if is-at-least 5.2; then
        _arguments_options=(-s -S -C)
    else
        _arguments_options=(-s -C)
    fi

    local context curcontext="$curcontext" state line
    _arguments "${_arguments_options[@]}" : \
'-h[Print help]' \
'--help[Print help]' \
'-V[Print version]' \
'--version[Print version]' \
":: :_oxygen_commands" \
"*::: :->oxygen" \
&& ret=0
    case $state in
    (oxygen)
        words=($line[1] "${words[@]}")
        (( CURRENT += 1 ))
        curcontext="${curcontext%:*:*}:oxygen-command-$line[1]:"
        case $line[1] in
            (completions)
_arguments "${_arguments_options[@]}" : \
'-h[Print help]' \
'--help[Print help]' \
':shell:(fish bash zsh)' \
&& ret=0
;;
(help)
_arguments "${_arguments_options[@]}" : \
":: :_oxygen__help_commands" \
"*::: :->help" \
&& ret=0

    case $state in
    (help)
        words=($line[1] "${words[@]}")
        (( CURRENT += 1 ))
        curcontext="${curcontext%:*:*}:oxygen-help-command-$line[1]:"
        case $line[1] in
            (completions)
_arguments "${_arguments_options[@]}" : \
&& ret=0
;;
(help)
_arguments "${_arguments_options[@]}" : \
&& ret=0
;;
        esac
    ;;
esac
;;
        esac
    ;;
esac
}

(( $+functions[_oxygen_commands] )) ||
_oxygen_commands() {
    local commands; commands=(
'completions:' \
'help:Print this message or the help of the given subcommand(s)' \
    )
    _describe -t commands 'oxygen commands' commands "$@"
}
(( $+functions[_oxygen__completions_commands] )) ||
_oxygen__completions_commands() {
    local commands; commands=()
    _describe -t commands 'oxygen completions commands' commands "$@"
}
(( $+functions[_oxygen__help_commands] )) ||
_oxygen__help_commands() {
    local commands; commands=(
'completions:' \
'help:Print this message or the help of the given subcommand(s)' \
    )
    _describe -t commands 'oxygen help commands' commands "$@"
}
(( $+functions[_oxygen__help__completions_commands] )) ||
_oxygen__help__completions_commands() {
    local commands; commands=()
    _describe -t commands 'oxygen help completions commands' commands "$@"
}
(( $+functions[_oxygen__help__help_commands] )) ||
_oxygen__help__help_commands() {
    local commands; commands=()
    _describe -t commands 'oxygen help help commands' commands "$@"
}

if [ "$funcstack[1]" = "_oxygen" ]; then
    _oxygen "$@"
else
    compdef _oxygen oxygen
fi
