name: CI

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build
        run: nix develop --command make build

      - name: Test
        run: nix develop --command make test

      - name: Docs
        run: nix develop --command make docs

      - name: Audit
        run: nix develop --command make audit

      - name: Memcheck
        run: nix develop --command make memcheck

      - name: Completions
        run: nix develop --command make gen_completions
